import { SERVICE as BASE_SERVICE } from '@lindeneg/funkallero';

const SERVICE = {
    ...BASE_SERVICE,
    COOKIE_MIDDLEWARE: 'COOKIE_MIDDLEWARE',
    TEST_1_MIDDLEWARE: 'TEST_1_MIDDLEWARE',
    TEST_2_MIDDLEWARE: 'TEST_2_MIDDLEWARE',
    DATA_CONTEXT_SEED: 'DATA_CONTEXT_SEED',
    TEMPLATE: 'TEMPLATE',
} as const;

export default SERVICE;
