import { SERVICE as BASE_SERVICE } from '@lindeneg/funkallero';

const SERVICE = {
    ...BASE_SERVICE,
    DATA_CONTEXT_SEED: 'DATA_CONTEXT_SEED',
    EXAMPLE_SCOPED_SERVICE: 'EXAMPLE_SCOPED_SERVICE',
    EXAMPLE_SINGLETON_SERVICE: 'EXAMPLE_SINGLETON_SERVICE',
} as const;

export default SERVICE;
