name: E2E

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  cache: 'yarn'

            - name: Bootstrap
              run: yarn bootstrap:ci
            - name: Build
              run: yarn build core funkallero auth-service example && yarn build e2e
            - name: Test
              run: yarn test e2e
