name: Benchmark Master

on:
    pull_request:
        branches:
            - master

jobs:
    benchmark_current:
        uses: ./.github/workflows/gh-actions-benchmark.yml
        with:
            ref_name: master
            start: example
            report: current
            dependencies: core funkallero auth-service
            optionalCommands: yarn cli build:mock example

    benchmark_latest:
        uses: ./.github/workflows/gh-actions-benchmark.yml
        with:
            ref_name: ${{ github.ref }}
            start: example
            report: latest
            dependencies: core funkallero auth-service
            optionalCommands: yarn cli build:mock example

    compare_master:
        needs: [benchmark_current, benchmark_latest]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4.7.0

            - name: Get Current report
              uses: actions/download-artifact@master
              with:
                  name: current
                  path: ./locust/report

            - name: Get Latest report
              uses: actions/download-artifact@master
              with:
                  name: latest
                  path: ./locust/report

            - name: Current <- Latest
              run: yarn bench compare current latest
