name: Benchmark Express

on:
    pull_request:
        branches:
            - master

jobs:
    benchmark:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/workflows/gh-actions-benchmark.yml
              name: Setup report from master
              with:
                  ref_name: ${{ github.ref_name }}
                  report_1: express
                  report_2: current
                  compare: express
