name: Benchmark

on:
    workflow_call:
        inputs:
            ref_name:
                description: 'The name of the branch to benchmark'
                type: string
                required: true
            start:
                description: 'Start command'
                type: string
                required: true
            report:
                description: 'Report name'
                type: string
                required: true
            dependencies:
                description: 'Dependencies'
                type: string
                required: true
            optionalCommands:
                description: 'Optional Commands'
                type: string
                required: false
                default: ''

jobs:
    benchmark:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ inputs.ref_name }}

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  cache: 'yarn'

            - name: Setup Python
              uses: actions/setup-python@v4.7.0

            - name: Bootstrap
              run: yarn bootstrap:ci && pip3 install -r ./locust/requirements.txt

            - name: Build
              run: yarn build ${{ inputs.dependencies }}

            - name: Optional Commands
              if: ${{ inputs.optionalCommands != '' }}
              run: ${{ inputs.optionalCommands }}

            - name: Report ${{ inputs.report }}
              run: yarn bench test ${{ inputs.start }} ${{ inputs.report }}

            - uses: actions/upload-artifact@master
              with:
                  name: ${{ inputs.report }}
                  path: ./locust/report/${{ inputs.report }}.json
