name: Benchmark Express

on:
    pull_request:
        branches:
            - master

jobs:
    benchmark_express:
        uses: ./.github/workflows/gh-actions-benchmark.yml
        with:
            ref_name: ${{ github.ref }}
            start: express
            report: express
            dependencies: express

    benchmark_example:
        uses: ./.github/workflows/gh-actions-benchmark.yml
        with:
            ref_name: ${{ github.ref }}
            start: example
            report: current
            dependencies: core funkallero auth-service
            optionalCommands: yarn cli build:mock example

    compare_express:
        needs: [benchmark_express, benchmark_example]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4.7.0

            - name: Get Express report
              uses: actions/download-artifact@master
              with:
                  name: express
                  path: ./locust/report

            - name: Get Current report
              uses: actions/download-artifact@master
              with:
                  name: current
                  path: ./locust/report

            - name: Express <- Current
              run: yarn bench compare express
